## Development Compose Environment
##

version: '2'

services:
  web:
    image: odoo:11.0
    depends_on:
      - db
    ports: 
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/data
      - odoo-addons:/mnt/extra-addons
      - './test/odoo.conf:/etc/odoo/odoo.conf:ro'
      - ./unit:/mnt/extra-addons/unit
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - "odoo-db-data:/var/lib/postgresql/data/pgdata:rw"



volumes:
  odoo-db-data:
    driver: local-persist
    driver_opts: 
      mountpoint: $PWD/local/pgdata
  odoo-web-data:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/local/data
  odoo-config:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/local/etc
  odoo-addons:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/local/addons
